### ISSUE TITLE
Arrow symbol too long

### ISSUE THREAD

**Issue by trunglh88** [AmrEldib/cmder-powershell-powerline-prompt#1]
Hi !
After i setup up files look like it working, but i has problems with arrow symbol if is not git folder.
How can i fix this ?

sorry for my english.

thank you.
![screenshot_1](https://user-images.githubusercontent.com/5045717/31713994-5a53b822-b42a-11e7-8adb-2bfc5f8ffa54.jpg)

**Comment by AmrEldib** [comment]
@Vocal yeah, I noticed that some times the arrow symbol looks too long. Is this on Windows 10? I can test there.

**Comment by modernist** [comment]
The issue also appears in git folders - in fact, the deeper into the folder hierarchy you navigate the longer the arrow - it gets longer by one character for each level. I am guessing it is related to #2 as well. This is on Windows 10.
![cmder](https://user-images.githubusercontent.com/1212380/34605440-4fbc7e1c-f214-11e7-8675-7d8aad52d9ce.png)

**Comment by AmrEldib** [comment]
@modernist does [this pull request](https://github.com/AmrEldib/cmder-powershell-powerline-prompt/pull/3) address this issue?

**Comment by AmrEldib** [comment]
@modernist I've merged that pull request. Maybe test using the latest version?

**Comment by modernist** [comment]
The latest PR seems to fix the issue, thanks for the update!

**Comment by Abdelrhmangad** [comment]
How can i make my cmder looks like this, please?!
