### ISSUE TITLE
Arrow symbol disconnect

### ISSUE THREAD

**Issue by shilucus** [AmrEldib/cmder-powershell-powerline-prompt#2]
Hi ,
After I set the file, it started working, but some problems like this:
![image](https://user-images.githubusercontent.com/14304571/33246731-380b71f4-d353-11e7-934c-cd15cb8f4bab.png)

How can i fix this ?

thank you.

**Comment by AmrEldib** [comment]
@shilucus it seems like it writing the arrow letter twice. Do you have any other files or functions modifying the prompt?

**Comment by AmrEldib** [comment]
@shilucus does [this pull request](https://github.com/AmrEldib/cmder-powershell-powerline-prompt/pull/3) address this issue?

**Comment by AmrEldib** [comment]
@shilucus I've merged that pull request. Maybe test using the latest version?

**Comment by shilucus** [comment]
@AmrEldib 
First of all, 
I'm very sorry that I didn't pay attention to GitHub for a long time.
After the update Cmder can be displayed normally.It's great！
Thank you very much！
